version: 0.2

phases:
  install:
    commands:
      - echo Cleaning project...
      - mvn clean
  pre_build:
    commands:
      - echo Installing Maven dependencies...
      - mvn install
  build:
    commands:
      - echo Build started
      - echo Compiling with mvn compile 
      - mvn compile
  post_build:
    commands:
      - echo Generating .jar
      - mvn package
      - echo Build completed
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/target/spring-application.jar
